language: android

script:
    - ./gradlew assembleDebug

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "./app/build/outputs/apk/debug/app-debug.apk"
  skip_cleanup: true
  on:
    all_branches: true