language: android

stages:
  - developBuild
    if: branch = develop
  - developRelease
    if: branch = master
  - name: deploy
    if: branch = master


jobs:
  include:
    - stage: developBuild
      script: ./gradlew assembleDebug
    - stage: developRelease
      script: ./gradlew assembleRelease
    - stage: deploy
      script: ./deploy

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "app/build/outputs/apk/**/*.apk"
  skip_cleanup: true
  on:
    branch: master